services:
  - type: web
    name: scrape # Or your service name
    env: node
    plan: free # Or your chosen plan
    buildCommand: npm install --cache /opt/render/project/src/.npm --prefer-offline false && npm run build # Example, adjust as needed, ensure clean install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18 # Or your preferred version
      # You can also try setting PUPPETEER_CACHE_DIR explicitly if issues persist,
      # though /opt/render/.cache/puppeteer should be the default Render uses.
      # - key: PUPPETEER_CACHE_DIR
      #   value: /opt/render/.cache/puppeteer
